feat(databases): Add support for fast bulk operations
feathersjs/feathers pull request #2945
Opened 2022-12-20 05:31 UTC by daffl

This pull request adds the ability to the built in database adapters to perform fast bulk operations for `create`, `patch` and `remove` by passing `params.bulk = true`. Bulk operations will use the fastest database call available and - when successful - will always return no data (an empty array) and not send real time event.

2022-12-20 17:06 UTC, marshallswain requested changes

2022-12-20 17:06 UTC, marshallswain commented on packages/memory/src/index.ts
> +    const payload = Array.isArray(_data) ? _data : [_data]
To skip the extra processing for large arrays, we can add another check for `params.bulk` before running `.map`:

```ts
const payload = Array.isArray(_data) ? _data : [_data]
const results = (params.bulk ? [] : payload).map((value) => {
  const id = (value as any)[this.id] || this._uId++
  const current = _.extend({}, value, { [this.id]: id })

  return _select((this.store[id] = current), params, this.id)
})

return params.bulk ? [] : Array.isArray(_data) ? results : results[0]
```

2022-12-20 17:06 UTC, marshallswain commented on packages/memory/src/index.ts
> +    const payload = Array.isArray(_data) ? _data : [_data]
It looks like we also need to address the scenario where we create a single record and also pass `params.bulk`:

```ts
const david = await service.create(
  {
    name: 'David',
    age: 3,
    created: true
  }, 
  { bulk: true }
)
```

We don't want to return an empty array for the above scenario since that breaks the request-to-response plurality mapping of the service interface.  So we probably ought to throw an error:

```ts
if (!Array.isArray(_data) && params.bulk) {
  throw new BadRequest()
}
```

2022-12-20 17:06 UTC, marshallswain commented on packages/adapter-commons/src/service.ts
> +    if (params.bulk) {
Maybe we can update `allowMulti` to accept `context.id` and have a centralized place to throw an error whenever `params.bulk === true` and

- For create: `data` is an object
- For patch and remove: `context.id` is null

2023-02-18 17:47 UTC, e-kibet commented
Lets also solve the merge conflicts

2023-12-21 16:21 UTC, MarcGodard commented
Any ETA on this? Running to issues where this would help.

2024-01-29 15:51 UTC, MarcGodard commented
This is more than a year old, can I make the requested changes?

2026-09-11 19:28 UTC, closed without merging